test_source: KB
agent_type: MCTS
test_list_path: config/smoke/test_list_kbl2_sample5.txt
dtype_str: fp32
gpu_name: NVIDIA GeForce RTX 2050
gpu_architecture: Ampere
gpu_ids:
- 0
num_processes: 1
use_remote_eval: true
remote_eval_url: http://127.0.0.1:12017
server_type: openrouter
model_name: "nvidia/nemotron-3-ultra-550b-a55b:free"
max_completion_tokens: 16384

total_steps: 5
max_memory_round: 5
pool_size: 5
disable_reviewer: false

save_path: outputs/MCTS_kbl2_sample5_openrouter
general_memory_path: results/memory/general_memory_v1_200.txt
memory_update: false
knowledge_1_threshold: 3

debug: false
exploration_weight: 0.3
expand_exploration_ratio: 1.0
reward_alpha: 0.0
small_step_limit: 2
p_large: 0.2
pool_size_extra_max: 0
softmax_temperature: 1.0
dummy: false
geometric_p: 0.6
